# Generated by Django 5.2.7 on 2025-10-21 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabungan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jenis', models.CharField(choices=[('KREDIT', 'Kredit'), ('DEBIT', 'Debit')], max_length=10)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabungan.buku')),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
    ]
