# Generated by Django 5.2.7 on 2025-10-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabungan', '0002_transaksi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('isi', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tabungan_catatan',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.AlterModelTable(
            name='buku',
            table='tabungan_buku',
        ),
        migrations.AlterModelTable(
            name='transaksi',
            table='tabungan_transaksi',
        ),
    ]
