# Generated by Django 5.2.7 on 2025-11-04 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_prodi', models.CharField(max_length=100)),
                ('kaprodi', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Program Studi',
            },
        ),
        migrations.CreateModel(
            name='Kuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matkul', models.CharField(max_length=100)),
                ('hari', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu')], max_length=10)),
                ('sks', models.IntegerField()),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mata_kuliah', to='api.prodi')),
            ],
            options={
                'verbose_name_plural': 'Kuliah',
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=20, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa', to='api.prodi')),
            ],
            options={
                'verbose_name_plural': 'Siswa',
            },
        ),
        migrations.CreateModel(
            name='Registrasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_registrasi', models.DateTimeField(auto_now_add=True)),
                ('kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrasi', to='api.kuliah')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrasi', to='api.siswa')),
            ],
            options={
                'verbose_name_plural': 'Registrasi',
                'unique_together': {('student', 'kuliah')},
            },
        ),
    ]
