# Generated by Django 5.2.7 on 2025-11-11 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kaprodi', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Prodi',
                'db_table': 'akademik_prodi',
            },
        ),
        migrations.CreateModel(
            name='Kuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mata_kuliah', models.CharField(max_length=100)),
                ('hari', models.CharField(choices=[('SENIN', 'Senin'), ('SELASA', 'Selasa'), ('RABU', 'Rabu'), ('KAMIS', 'Kamis'), ('JUMAT', 'Jumat'), ('SABTU', 'Sabtu')], max_length=10)),
                ('sks', models.IntegerField()),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.prodi')),
            ],
            options={
                'verbose_name_plural': 'Kuliah',
                'db_table': 'akademik_kuliah',
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=20, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/siswa/')),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.prodi')),
            ],
            options={
                'verbose_name_plural': 'Siswa',
                'db_table': 'akademik_siswa',
            },
        ),
        migrations.CreateModel(
            name='Registrasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_registrasi', models.DateField(auto_now_add=True)),
                ('kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.kuliah')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.siswa')),
            ],
            options={
                'verbose_name_plural': 'Registrasi',
                'db_table': 'akademik_registrasi',
                'unique_together': {('student', 'kuliah')},
            },
        ),
    ]
