# Generated by Django 5.2.7 on 2025-11-01 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drfpost',
            options={'ordering': ['-uploaded']},
        ),
    ]
