# Generated by Django 5.2.7 on 2025-11-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_api', '0002_alter_drfpost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='drfpost',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='book_photos/'),
        ),
    ]
