# Generated by Django 5.2.7 on 2025-11-05 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berita',
            options={},
        ),
        migrations.AlterModelOptions(
            name='komentar',
            options={},
        ),
        migrations.RemoveField(
            model_name='berita',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='berita',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='komentar',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='berita',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='berita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='berita.berita'),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
