# Generated by Django 5.2.7 on 2025-10-16 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_api', '0002_drfdosen_drfstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='drfstudent',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='basic_api.drfdosen'),
        ),
    ]
