# Generated by Django 5.2.7 on 2025-10-16 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_api', '0003_drfstudent_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drfstudent',
            name='mentor',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='basic_api.drfdosen'),
        ),
    ]
