# Generated by Django 5.2.7 on 2025-10-23 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_api', '0007_alter_drfstudent_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='drfdosen',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='drfstudent',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='basic_api.drfdosen'),
        ),
    ]
