# Generated by Django 5.2.7 on 2025-10-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_api', '0009_remove_drfdosen_image_drfstudent_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drfstudent',
            name='image',
        ),
        migrations.AddField(
            model_name='drfpost',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='image/'),
        ),
    ]
